#!/bin/bash
montage photobooth_images/image*.jpg -tile 3x1 -geometry +50+40 -background White photobooth_images/temp_montage2.jpg
montage layouts/banner_gd.png -tile 1x1 -geometry +0+90 -background White layouts/banner_new.jpg
montage photobooth_images/temp_montage2.jpg layouts/banner_new.jpg -tile 2x1 -geometry +0+0 -background White photobooth_images/temp_montage3.jpg
montage photobooth_images/temp_montage3.jpg layouts/line.png photobooth_images/temp_montage3.jpg -tile 1x3 -geometry +0+20 -background White -border 0 photobooth_images/temp_montage4.jpg

#lp -d Canon_CP1000 photobooth_images/temp_montage4.jpg
suffix=$(date +%H%M%S)
cp photobooth_images/temp_montage4.jpg archive/PB_${suffix}.jpg

#mogrify -rotate 90 photobooth_images/image1.jpg
#mogrify -rotate 90 photobooth_images/image2.jpg
#mogrify -rotate 90 photobooth_images/image3.jpg
#rm /home/pi/Desktop/photobooth_images/*.jpg